highlighter: pygments
github: [Repository metadata]
safe: true
lsi: false
paginate: 10
paginate_path: "/blog/page/:num"
categories: [copywriting, marketing, other, writing]
url:        http://www.tylermoore.website