highlighter: rouge
github: [Repository metadata]
safe: false
lsi: false
paginate: 10
paginate_path: "/blog/page/:num"
categories: [copywriting, marketing, programming, other, writing]
url:        http://www.tylermoore.website
gems:
  - jekyll-sitemap
  - jekyll-redirect-from